Feat(publication): Add support for simplify link algorithm
BibCnrs/BibCnrs pull request #215
Opened 2024-09-11 15:07 UTC by jonathan-marmelab

## Problem

Current link priorization algorithm is too complex

## Solution

Implement and easier algorithm

2024-09-11 16:55 UTC, ThieryMichel requested changes

2024-09-11 16:55 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +	for (let i = 1; i < links.length; i++) {
Nitpick: A reduce would be easier to follow IMO

2024-09-11 16:55 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function prioritizeLinksWithSameCoverageEnd(links: Link[]) {
Since we always return only one item, we should just return it without wrapping it in an array.
This would make it clearer

2024-09-11 16:55 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function prioritizeLinksWithSameCoverageEnd(links: Link[]) {
Also how about renaming it to getPriorityLink?

2024-09-11 16:55 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function prioritizeLinksWithDifferentCoverageEnd(links: Link[]) {
I would split this operation in two, one to filter out the duplicated links, and one to order them.

2024-09-12 07:51 UTC, ThieryMichel requested changes

2024-09-12 07:51 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function getPriorityLinkWhenSameCoverageEnd(links: Link[]) {
Can you add test on this function?
Also, it could return undefined if the array is empty.

2024-09-12 07:51 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function getPriorityLinksWhenDifferentCoverageEnd(links: Link[]) {
Can you add tests on this function ?

2024-09-12 07:51 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +		return [getPriorityLinkWhenSameCoverageEnd(links)];
If receiving an empty array, getPriorityLinkWhenSameCoverageEnd would return undefined.

2024-09-12 08:18 UTC, jonathan-marmelab commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function getPriorityLinkWhenSameCoverageEnd(links: Link[]) {
This function is internal and tested with is calling function

2024-09-12 08:18 UTC, jonathan-marmelab commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function getPriorityLinksWhenDifferentCoverageEnd(links: Link[]) {
This function is internal and tested with is calling function

2024-09-12 08:19 UTC, jonathan-marmelab commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +		return [getPriorityLinkWhenSameCoverageEnd(links)];
This cannot happen as the array length is checked before

2024-09-12 08:25 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +		return [getPriorityLinkWhenSameCoverageEnd(links)];
A function should not depends on knowledge, of who is calling it and on what condition.
It's more robust that way.

2024-09-12 08:26 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function getPriorityLinksWhenDifferentCoverageEnd(links: Link[]) {
Not all the case imo

2024-09-12 08:27 UTC, ThieryMichel commented on packages/front/src/app/pages/search/publication/prioritizeLinksV2.ts
> +function getPriorityLinkWhenSameCoverageEnd(links: Link[]) {
Not all case are covered IMO

2024-09-12 12:52 UTC, ThieryMichel approved these changes

2024-09-12 12:53 UTC, ThieryMichel approved these changes

2024-09-12 12:53 UTC, merged